version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grindwork
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: grindwork-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/grindwork
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8085:8085" # Porta do backend
      - "5173:5173" # Porta do frontend

volumes:
  mysql_data:
