INSERT INTO localidade (cidade, estado, pais) VALUES
('Abadia de Goiás', 'Goiás', 'Brasil'),
('Abadiânia', 'Goiás', 'Brasil'),
('Acreúna', 'Goiás', 'Brasil'),
('Adelândia', 'Goiás', 'Brasil'),
('Água Fria de Goiás', 'Goiás', 'Brasil'),
('Água Limpa', 'Goiás', 'Brasil'),
('Alexânia', 'Goiás', 'Brasil'),
('Aloândia', 'Goiás', 'Brasil'),
('Alto Horizonte', 'Goiás', 'Brasil'),
('Alto Paraíso de Goiás', 'Goiás', 'Brasil'),
('Amanhã', 'Goiás', 'Brasil'),
('Anápolis', 'Goiás', 'Brasil'),
('Anhanguera', 'Goiás', 'Brasil'),
('Aparecida de Goiânia', 'Goiás', 'Brasil'),
('Araçu', 'Goiás', 'Brasil'),
('Aragarças', 'Goiás', 'Brasil'),
('Aruanã', 'Goiás', 'Brasil'),
('Aurilândia', 'Goiás', 'Brasil'),
('Avelinópolis', 'Goiás', 'Brasil'),
('Baliza', 'Goiás', 'Brasil'),
('Barro Alto', 'Goiás', 'Brasil'),
('Bela Vista de Goiás', 'Goiás', 'Brasil'),
('Bom Jardim de Goiás', 'Goiás', 'Brasil'),
('Bonfinópolis', 'Goiás', 'Brasil'),
('Bonópolis', 'Goiás', 'Brasil'),
('Brazabrantes', 'Goiás', 'Brasil'),
('Britânia', 'Goiás', 'Brasil'),
('Buriti Alegre', 'Goiás', 'Brasil'),
('Buritinópolis', 'Goiás', 'Brasil'),
('Cabeceiras', 'Goiás', 'Brasil'),
('Cachoeira Alta', 'Goiás', 'Brasil'),
('Cachoeira de Goiás', 'Goiás', 'Brasil'),
('Caçu', 'Goiás', 'Brasil'),
('Caldazinha', 'Goiás', 'Brasil'),
('Campestre de Goiás', 'Goiás', 'Brasil'),
('Campinaçu', 'Goiás', 'Brasil'),
('Campo Alegre de Goiás', 'Goiás', 'Brasil'),
('Campo Limpo de Goiás', 'Goiás', 'Brasil'),
('Campos Belos', 'Goiás', 'Brasil'),
('Campos Verdes', 'Goiás', 'Brasil'),
('Cezarina', 'Goiás', 'Brasil'),
('Chapadão do Céu', 'Goiás', 'Brasil'),
('Cidade Ocidental', 'Goiás', 'Brasil'),
('Cocalzinho de Goiás', 'Goiás', 'Brasil'),
('Colinas do Sul', 'Goiás', 'Brasil'),
('Corumbá de Goiás', 'Goiás', 'Brasil'),
('Cristalina', 'Goiás', 'Brasil'),
('Cromínia', 'Goiás', 'Brasil'),
('Cumari', 'Goiás', 'Brasil'),
('Damolândia', 'Goiás', 'Brasil'),
('Divinópolis de Goiás', 'Goiás', 'Brasil'),
('Doverlândia', 'Goiás', 'Brasil'),
('Edealina', 'Goiás', 'Brasil'),
('Edéia', 'Goiás', 'Brasil'),
('Estrela do Norte', 'Goiás', 'Brasil'),
('Firminópolis', 'Goiás', 'Brasil'),
('Flores de Goiás', 'Goiás', 'Brasil'),
('Formosa', 'Goiás', 'Brasil'),
('Formoso', 'Goiás', 'Brasil'),
('Gameleira de Goiás', 'Goiás', 'Brasil'),
('Goianápolis', 'Goiás', 'Brasil'),
('Goiás', 'Goiás', 'Brasil'),
('Goianésia', 'Goiás', 'Brasil'),
('Goiânia', 'Goiás', 'Brasil'),
('Goianira', 'Goiás', 'Brasil'),
('Guapó', 'Goiás', 'Brasil'),
('Guaraíta', 'Goiás', 'Brasil'),
('Guarani de Goiás', 'Goiás', 'Brasil'),
('Heitoraí', 'Goiás', 'Brasil'),
('Hidrolândia', 'Goiás', 'Brasil'),
('Hidrolina', 'Goiás', 'Brasil'),
('Iaciara', 'Goiás', 'Brasil'),
('Inhumas', 'Goiás', 'Brasil'),
('Itaberaí', 'Goiás', 'Brasil'),
('Itaguari', 'Goiás', 'Brasil'),
('Itapaci', 'Goiás', 'Brasil'),
('Itapirapuã', 'Goiás', 'Brasil'),
('Itapuranga', 'Goiás', 'Brasil'),
('Itumbiara', 'Goiás', 'Brasil'),
('Jandaia', 'Goiás', 'Brasil'),
('Jaraguá', 'Goiás', 'Brasil'),
('Jesúpolis', 'Goiás', 'Brasil'),
('Joviânia', 'Goiás', 'Brasil'),
('Junqueiro', 'Goiás', 'Brasil'),
('Lagoa Santa', 'Goiás', 'Brasil'),
('Leolândia', 'Goiás', 'Brasil'),
('Luziânia', 'Goiás', 'Brasil'),
('Mairipotaba', 'Goiás', 'Brasil'),
('Mambaí', 'Goiás', 'Brasil'),
('Mara Rosa', 'Goiás', 'Brasil'),
('Marzagão', 'Goiás', 'Brasil'),
('Matrinchã', 'Goiás', 'Brasil'),
('Mineiros', 'Goiás', 'Brasil'),
('Moiporá', 'Goiás', 'Brasil'),
('Montes Claros de Goiás', 'Goiás', 'Brasil'),
('Montividiu', 'Goiás', 'Brasil'),
('Montividiu do Norte', 'Goiás', 'Brasil'),
('Morro Agudo de Goiás', 'Goiás', 'Brasil'),
('Mossâmedes', 'Goiás', 'Brasil'),
('Nazaré', 'Goiás', 'Brasil'),
('Niquelândia', 'Goiás', 'Brasil'),
('Nova América', 'Goiás', 'Brasil'),
('Nova Aurora', 'Goiás', 'Brasil'),
('Nova Crixás', 'Goiás', 'Brasil'),
('Nova Glória', 'Goiás', 'Brasil'),
('Nova Iguaçu de Goiás', 'Goiás', 'Brasil'),
('Novo Brasil', 'Goiás', 'Brasil'),
('Novo Gama', 'Goiás', 'Brasil'),
('Ouro Verde de Goiás', 'Goiás', 'Brasil'),
('Ouvidor', 'Goiás', 'Brasil'),
('Padre Bernardo', 'Goiás', 'Brasil'),
('Palminópolis', 'Goiás', 'Brasil'),
('Panorama do Oeste', 'Goiás', 'Brasil'),
('Paraúna', 'Goiás', 'Brasil'),
('Paranaiguara', 'Goiás', 'Brasil'),
('Pires do Rio', 'Goiás', 'Brasil'),
('Planaltina', 'Goiás', 'Brasil'),
('Pontalina', 'Goiás', 'Brasil'),
('Porangatu', 'Goiás', 'Brasil'),
('Posse', 'Goiás', 'Brasil'),
('Professor Jamil', 'Goiás', 'Brasil'),
('Quirinópolis', 'Goiás', 'Brasil'),
('Rialma', 'Goiás', 'Brasil'),
('Rio Verde', 'Goiás', 'Brasil'),
('Rubiataba', 'Goiás', 'Brasil'),
('Samambaia', 'Goiás', 'Brasil'),
('Santa Bárbara de Goiás', 'Goiás', 'Brasil'),
('Santa Cruz de Goiás', 'Goiás', 'Brasil'),
('Santa Helena de Goiás', 'Goiás', 'Brasil'),
('Santa Isabel', 'Goiás', 'Brasil'),
('Santa Rita do Novo Destino', 'Goiás', 'Brasil'),
('Santa Rosa de Goiás', 'Goiás', 'Brasil'),
('Santo Antônio do Descoberto', 'Goiás', 'Brasil'),
('São Domingos', 'Goiás', 'Brasil'),
('São Francisco de Goiás', 'Goiás', 'Brasil'),
('São João da Paraúna', 'Goiás', 'Brasil'),
('São Luís de Montes Belos', 'Goiás', 'Brasil'),
('São Miguel do Araguaia', 'Goiás', 'Brasil'),
('São Patrício', 'Goiás', 'Brasil'),
('São Simão', 'Goiás', 'Brasil'),
('Silvânia', 'Goiás', 'Brasil'),
('Simolândia', 'Goiás', 'Brasil'),
("Sítio d'Abadia", 'Goiás', 'Brasil'),
('Taquaral de Goiás', 'Goiás', 'Brasil'),
('Teresina de Goiás', 'Goiás', 'Brasil'),
('Três Ranchos', 'Goiás', 'Brasil'),
('Turvânia', 'Goiás', 'Brasil'),
('Uruaçu', 'Goiás', 'Brasil'),
('Uruana', 'Goiás', 'Brasil'),
('Valparaíso de Goiás', 'Goiás', 'Brasil'),
('Varjão', 'Goiás', 'Brasil'),
('Vianópolis', 'Goiás', 'Brasil'),
('Vila Boa', 'Goiás', 'Brasil'),
('Vila Propício', 'Goiás', 'Brasil');